twig:
    default_path: '%kernel.project_dir%/templates'
    form-themes: ['bootstrap_5_layout.html.twig']
    date:
        timezone: Europe/Moscow

when@test:
    twig:
        strict_variables: true
